### PR TITLE
Add CHANGE_BRANCH and CHANGE_FORK descriptions

### PR DESCRIPTION
**Pull request by v1v**
`CHANGE_BRANCH` and `CHANGE_FORK` env variables don't have any references in the `<JENKINS_URL>/pipeline-syntax/globals` page.

Their descriptions are already in the declarative plugin:
- https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/master/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeRequestConditional/help-fork.html
- https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/master/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/ChangeRequestConditional/help-branch.html

How does it look like now?

image

### CODE REVIEW

**Comment by bitwiseman** [comment]
@v1v have you tested this outside of the conditions in declarative?

**Comment by v1v** [comment]
As far as I see those env variables are declared:
- https://github.com/jenkinsci/branch-api-plugin/blob/64eaa48c829c7ec4be7c203d01f33ae55d4cd04e/src/main/java/jenkins/branch/BranchNameContributor.java#L68-L74

but no docs are showing what they do. 

I managed to find that particular misleading in the docs when I used those env variables in some Multibranch pipelines using the github branch source. Answering your question, I actually didn't run any other tests than ensuring the help page was showing those details as I didn't change anything in the logic of the plugin but the docs.

**Comment by bitwiseman** [comment]
Ah, your original link specified pipeline-model-definition sources not branch-api.  Cool.

**Comment by v1v** [comment]
Sorry about the misleading description

**Comment by v1v** [comment]
@dwnusbaum seems you are in the loop to review this PR, please let me know your thoughts. 

Cheers

**Pull request merged**
