### PR TITLE
[JENKINS-38837] Add a configuration option for workspaces on master

### PR DESCRIPTION
**Pull request by rsandell**
[JENKINS-38837](https://issues.jenkins-ci.org/browse/JENKINS-38837)

Because of the fix for [JENKINS-34564](https://issues.jenkins-ci.org/browse/JENKINS-34564) multi branch workspace names don't really fit into how normally workspace paths on the master are calculated.
So instead this introduces the option to configure where to put them as that would solve the original reporters issue with needing to put them on another drive/path than JENKINS_HOME.

@reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
Test failed because it ran our of perm gen.

**Comment by jglick** [comment]
Switched it to JDK 8.

**Comment by rsandell** [comment]
Well, I've tried a couple of approaches, but haven't been able to come up with a solution that doesn't reintroduce JENKINS-34564 or pollutes the jobs directory.

**Comment by jglick** [comment]
I am looking into whether it is feasible to use the existing core configuration.

**Comment by jglick** [comment]
#103 is my counterproposal.

**Comment by stephenc** [comment]
Closing in favour of @jglick 's proposal

**Pull request closed without merging**
