### PR TITLE
[JENKINS-32782] Empty view did not show delete link

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-32782](https://issues.jenkins-ci.org/browse/JENKINS-32782)

Corrects handling of view identity which I commented on in #17.

@reviewbybees esp. @stephenc, @kzantow

### CODE REVIEW

**Comment by jglick** [comment]
By the way [this](https://github.com/jenkinsci/cloudbees-folder-plugin/blob/798b6a1a9c07de70ae291b4c43b6f4278753a347/src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/tasks-new.jelly#L29) is the code calling `equals` in this case.

**Comment by kzantow** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

(@stephenc will need your assistance today I think)

**Pull request merged**
