### PR TITLE
JENKINS-54052 - Honor quietPeriod when scheduling multibranch builds

### PR DESCRIPTION
**Pull request by atanasenko**

### CODE REVIEW

**Comment by stephenc** [comment]
Test failures seem legit

**Comment by KostyaSha** [comment]
> Test failures seem legit

Do you mean this?
```
[WARNING] Flakes: 

[WARNING] integration.BrandingTest.given_orgFolderWithI18nRepos_when_indexing_then_repoNamesEncoded(integration.BrandingTest)

[ERROR]   Run 1: BrandingTest.cleanOutAllItems:97 class integration.harness.BasicMultiBranchProject is missing its descriptor

[INFO]   Run 2: PASS

```

**Comment by bitwiseman** [comment]
@atanasenko Verified the test failures are real.  Please take a look.

**Comment by bitwiseman** [comment]
@stephenc @KostyaSha
Why would all these tests start failing (and passing on rerun) due to this one change?  I can't make sense of it.

**Comment by slide** [comment]
I see failures on tests when I build master locally (on Windows), but CI is not seeing it. I am not sure what the issue is.

**Comment by slide** [comment]
I believe the failures here are because the FreeStyleProject that is used in the tests does not have a quiet period set and when the quiet period is not set, Jenkins uses the default of 5 down in the class hierarchy somewhere. This seems to cause one of the tests to timeout, but it is not cleaned up correctly and so there are files in use that other tests try to clean up which can't be. I have worked around this by setting a quiet period of 0 for the FreeStyleProject used in the tests. This allows tests to pass. I will paste my fix after a meeting I have.

**Comment by atanasenko** [comment]
@slide oh cool, thanks for finding that

**Comment by slide** [comment]
I don't know if its a valid failure though, meaning, will the plugin not work in production in a similar way, someone with more knowledge would need to comment on that.

**Comment by bitwiseman** [comment]
@slide 
You didn't end up pasting in your fix.

**Comment by slide** [comment]
You are very correct, I hope I didn't delete that repo! Let me look for it

**Comment by slide** [comment]
```
diff --git a/src/test/java/integration/harness/BasicBranchProjectFactory.java b/src/test/java/integration/harness/BasicBranchProjectFactory.java
index b0f6658..bfc3ede 100644
--- a/src/test/java/integration/harness/BasicBranchProjectFactory.java
+++ b/src/test/java/integration/harness/BasicBranchProjectFactory.java
@@ -47,6 +47,10 @@ public class BasicBranchProjectFactory extends BranchProjectFactory<FreeStylePro
     public FreeStyleProject newInstance(Branch branch) {
         FreeStyleProject job = new FreeStyleProject(getOwner(), branch.getEncodedName());
         setBranch(job, branch);
+        try {
+            job.setQuietPeriod(0);
+        } catch(IOException e) {
+        }
         return job;
     }
 
```

**Comment by g-doc** [comment]
Hello, I would be very interested in getting this fix ! Any chance to have this PR merged ?

**Comment by bitwiseman** [comment]
Closing in favor of #190

**Pull request closed without merging**
