### PR TITLE
[JENKINS-39682] trigger after-save hooks and recalculate

### PR DESCRIPTION
**Pull request by daspilker**
... after `createProjectFromXML` or `updateByXml`.

See [JENKINS-39682](https://issues.jenkins-ci.org/browse/JENKINS-39682?focusedCommentId=369197&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-369197).

### CODE REVIEW

**Comment by bitwiseman** [comment]
@daspilker  
This could use some tests.

**Comment by darxriggs** [comment]
@bitwiseman apart from the tests what do you think about the change itself?

**Comment by daspilker** [comment]
@bitwiseman I added some tests. The tests will fail if you remove the fix. It turned out that the `ItemListener` is not necessary.

**Comment by bitwiseman** [comment]
@daspilker Not sure why this failed can you push an updated commit to run a new build?

**Comment by daspilker** [comment]
@bitwiseman there was an infrastructure problem yesterday. Now it's green.

**Comment by daspilker** [comment]
I rebase to current master and CI is green again.

**Comment by daspilker** [comment]
Pinging @bitwiseman and @dwnusbaum. Any news on this issue?

**Comment by michelzanini** [comment]
I have added a comment to https://issues.jenkins-ci.org/browse/JENKINS-39682 and will add it here as well, for visibility.

```
This PR was merged to fix an issue but has caused a worse one in my opinion.

My seed job runs every 4 hours, it scans repositories in Bitbucket and create and/or update hundreds of jobs as a result.

After updating the Branch API plugin to 2.5.5 with this PR included, now every 4 hours, ALL my ~ 250 jobs are triggering a branch scanning at the same time after seed job completes.

This causes several API calls to Bitbucket all at the same time and then they hang, as Bitbucket has a limit on number of API calls.

That means I have to revert the plugin to 2.5.4 as its impossible to continue with this behaviour.


I understand what you are trying to fix here - to run it initially when the job gets created for the first time. But it should not happen when the job gets updated.

Also, using a scan trigger fixes the problem of initial branch scanning and it is recommend to use one anyway (as sometimes Webhooks will be missed). It has never being a problem for us.

Anyway, I think this has made things worse at the point of being a blocker.

Thanks.
```

**Comment by sirstrahd** [comment]
This change also caused all sorts of trouble for us, since we have a job that updates our folder xml configs and this triggers a humongous amount of reindexings. In the end we just forked the plugin and commented this change out, which addressed our issues.

**Pull request merged**
