### PR TITLE
Baseline 2.332.4

### PR DESCRIPTION
**Pull request by jonesbusy**
Use a more recent baseline of jenkins (https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

### CODE REVIEW

**Comment by jonesbusy** [comment]
Ping @jenkinsci/branch-api-plugin-developers

**Comment by jonesbusy** [comment]
Friendly reminder @jenkinsci/branch-api-plugin-developers

**Comment by car-roll** [comment]
Hi @jonesbusy thanks for the PR! So I know documentation recommends `2.332.4`, I generally prefer `x.1` versions for greater compatibility. Looking at https://stats.jenkins.io/pluginversions/branch-api.html, I think I do prefer `2.332.1`. I just merged #341 which moves to `2.332.1`. I am going to close this PR, but feel free to leave a comment and re-open if you think the bump to `.4` is warranted.

**Comment by jonesbusy** [comment]
Thanks all good on my side, I just hope we can restore automatic releases.

**Pull request closed without merging**
