### PR TITLE
[JENKINS-72958] expose buildable property on MultiBranchProject to API

### PR DESCRIPTION
**Pull request by MarkRx**
Exposes the "buildable" field to the REST API indicating if the multi-branch job has been disabled

https://issues.jenkins.io/browse/JENKINS-73425

### Testing done
Create a multi-branch pipeline branch. Enable it. Disable it.

http://localhost:8080/jenkins/job/test/job/myprimarybranch/api/xml?tree=property[buildable[*]]

#### Enabled

```xml
<workflowMultiBranchProject _class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject">
    <buildable>true</buildable>
</workflowMultiBranchProject>
```

```json
{
    _class: "org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject",
    buildable: true
}
```

#### Disabled

```xml
<workflowMultiBranchProject _class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject">
    <buildable>false</buildable>
</workflowMultiBranchProject>
```

```json
{
    _class: "org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject",
    buildable: false
}
```

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by MarkRx** [comment]
@jglick @strangelookingnerd

**Comment by MarkRx** [comment]
@basil @jtnord @rsandell someone please review and merge thanks

**Comment by jtnord** [comment]
I am also confused as to why https://github.com/jenkinsci/branch-api-plugin/blob/46de1e829a4f3fcbecf7f001061be8c07b61b380/src/main/java/jenkins/branch/MultiBranchProject.java#L851 shows up in the API which is not tagged as `Exported` but overridden...

**Comment by jtnord** [comment]
@MarkRx https://github.com/jenkinsci/cloudbees-folder-plugin/pull/441 if you would like to try that instead.

**Comment by MarkRx** [comment]
@jtnord tested works thanks!

http://localhost:8080/jenkins/job/folder1/job/pipeline1/api/json?tree=buildable

Enabled:
```
{
    _class: "org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject",
    buildable: true
}
```

Disabled:
```
{
    _class: "org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject",
    buildable: true
}
```

Note child jobs will have buildable=true even if the parent is disabled (buildable=false). The buildable property doesn't propagate so the parent job needs to be checked. This is existing behavior and unrelated to exposing the buildable property.

**Pull request closed without merging**
