### PR TITLE
Enable configurable icons

### PR DESCRIPTION
**Pull request by strangelookingnerd**
I'm the maintainer of [custom-folder-icon-plugin](https://github.com/jenkinsci/custom-folder-icon-plugin) and wanted to enable my plugin to be used for Multi Branch / Organization Folders as well. This fix allows my plugin to be used with no hard dependencies added.
If there is any reason why it should not be possible to overwrite the icons, please let me know.
There are no Unit Tests as I honestly would not know how to test this, however I verified it manually and found no issue so far.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by strangelookingnerd** [comment]
Can I get feedback on this please?

@rsandell @jglick

**Comment by jglick** [comment]
> If there is any reason why it should not be possible to overwrite the icons, please let me know.

The icon at least for a GH organization folder will be set to that of the GH organization itself. Not sure if this change would interfere with that.

**Comment by strangelookingnerd** [comment]
> > If there is any reason why it should not be possible to overwrite the icons, please let me know.
> 
> The icon at least for a GH organization folder will be set to that of the GH organization itself. Not sure if this change would interfere with that.

No interference besides the fact that one would be able to change the icons default value if desired.

**Review by car-roll — APPROVED** [review]

**Comment by leslie-alldridge** [comment]
hey @car-roll and @strangelookingnerd we are using this plugin in Jenkins and we also have configurable icons. In the first image you can see the icons fail to load (due to cors issues contacting our private github enterprise). We however wish to use the default icon. If I change this in the UI and save it fixes the icon issue. 

When we re-deploy jenkins those changes aren't saved. It can be exhausting manually changing icons to default every release. Is there a way we can code-ify this ? The setting continues to revert back to our github icon

Your help would be appreciated

Cheers

Screen Shot 2022-05-04 at 9 18 59 AM
Screen Shot 2022-05-04 at 9 19 18 AM
Screen Shot 2022-05-04 at 9 22 12 AM

**Comment by strangelookingnerd** [comment]
@car-roll @leslie-alldridge I think this might be related to / fixed with #308

**Comment by leslie-alldridge** [comment]
Hey @strangelookingnerd that's all good I'm pleased to hear your response! Once it is released I will update our plugin to get the latest version with your fix 🎉

**Pull request merged**
